controller:
  simple_chassis_controller:
    type: simple_chassis_controller/SimpleChassisController
    state_: 1

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50